version: "3"
services:


  angulardevopsf:
    image: majdimsallem/frontf:27
    container_name: angulardevopsf
    env_file: ./.env
    ports:
      - $ANGULAR_LOCAL_PORT:$ANGULAR_DOCKER_PORT
   



